### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by acao** [acao/json-schema-workbench#1]
- [x] toggle between json4/json5 - Settings context? persist? per-editor or across editors? already implemented in json-editor.tsx
- [ ] allow reverting to system default after toggling theme. perhaps allow choosing from other themes?
- [ ] toggle editor theme based on light/dark theme
- [x] allow importing/exporting schema and/or value from json, json5, yaml, and other files
- [ ] allow loading schema (and value?) from a URL
- [ ] provide a count of validation issues
- [ ] allow expanding an issues panel for validation issues?
- [ ] provide a formatting button
- [x] replace logo
- [ ] navbar -> menu?
- [ ] provide context menu
- [x] persist settings and other states?
- [ ] allow saving schemas (and test values)?
- [x] migrate to zustand
- [x] adopt @uiw/ react-codemirror
